# Site settings
title: Kubernetes 101
email: support@nectar.org.au
description: Kubernetes 101

baseurl: ""
url: https://nectar-rc.github.io/kubernetes-101
git_address: https://github.com/NeCTAR-RC/kubernetes-101
git_edit_address: https://github.com/NeCTAR-RC/kubernetes-101/blob/gh-pages

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

timezone: Australia/Melbourne

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: docs
